[rospy.client][INFO] 2017-11-29 12:25:49,414: init_node, name[/rostopic_7529_1511976349396], pid[7529]
[xmlrpc][INFO] 2017-11-29 12:25:49,414: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-11-29 12:25:49,415: Started XML-RPC server [http://mdas-Meerkat:39255/]
[rospy.init][INFO] 2017-11-29 12:25:49,415: ROS Slave URI: [http://mdas-Meerkat:39255/]
[rospy.impl.masterslave][INFO] 2017-11-29 12:25:49,415: _ready: http://mdas-Meerkat:39255/
[xmlrpc][INFO] 2017-11-29 12:25:49,415: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-11-29 12:25:49,415: Registering with master node http://localhost:11311
[rospy.init][INFO] 2017-11-29 12:25:49,515: registered with master
[rospy.rosout][INFO] 2017-11-29 12:25:49,516: initializing /rosout core topic
[rospy.rosout][INFO] 2017-11-29 12:25:49,521: connected to core topic /rosout
[rospy.simtime][INFO] 2017-11-29 12:25:49,524: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-11-29 12:25:49,582: topic[/gps_fix_psr] adding connection to [http://mdas-Meerkat:33405/], count 0
[rospy.internal][INFO] 2017-11-29 12:25:49,734: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2017-11-29 12:25:57,978: signal_shutdown [signal-2]
[rospy.internal][INFO] 2017-11-29 12:25:57,986: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-11-29 12:25:57,988: topic[/gps_fix_psr] removing connection to http://mdas-Meerkat:33405/
[rospy.internal][WARNING] 2017-11-29 12:25:57,991: Unknown error initiating TCP/IP socket to mdas-Meerkat:50293 (http://mdas-Meerkat:33405/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2017-11-29 12:25:57,991: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 307, in close
    c.close()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 807, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2017-11-29 12:25:57,992: signal-2
[rospy.core][INFO] 2017-11-29 12:25:58,109: signal_shutdown [atexit]
